# Generated by Django 4.2.6 on 2023-10-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consumeruser',
            name='last_name',
        ),
    ]
