# Generated by Django 4.2.6 on 2023-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmeruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='farmeruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='farmeruser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='farmeruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='farmeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farmeruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='farmeruser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
