# Generated by Django 4.2.6 on 2023-10-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('farmer', '0002_alter_farmeruser_options_alter_farmeruser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeruser',
            name='groups',
            field=models.ManyToManyField(related_name='farmer_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='farmeruser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='farmer_users', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmeruser'),
        ),
    ]
